min_value: 2052.0
max_value: 3121.0
joint_state_topic: /left/gripper/dynamixel_motor/joint_states
command_topic: /left/gripper/dynamixel_motor/command
enable_torque_service: /left/gripper/dynamixel_motor/set_torque
max_delta: 0.8
